### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by lucaskyle** [clcarwin/sphereface_pytorch#13]
File  dataset.py  line 62, in __init__

self.nparrimage = np.frombuffer(self.arrimage.get_obj(),np.float32).reshape(10,len(self.arrimage)/10)
TypeError: 'float' object cannot be interpreted as an integer

**Comment by LingJiangXie** [comment]
Maybe you can change your python version to 2.7 .

**Comment by lucaskyle** [comment]
sorry, i m train to run the train.py using CASIA dataset
then i found this typeError
i changed this line into:  

len(self.arrimage)//10

it worked, and finished first epoch but stuck...

**Comment by lucaskyle** [comment]
亲

你好

前面跑了一下训练完模型.

99.15% 好棒啊！


不过 跑了一次train.py 时候报错了

把/改成// 跑了一次 只能完成第一次的epoch



我很仔细的读过了论文。

准备稍微改成4层的看看能不能有98%的准确率

而且十分喜欢 你定义的 a-softmaxloss

对照着论文看还是没看懂...


新年快乐，

恭喜发财.



________________________________
发件人: LingJiangXie <notifications@github.com>
发送时间: 2017年12月28日 8:43
收件人: clcarwin/sphereface_pytorch
抄送: lucaskyle; Author
主题: Re: [clcarwin/sphereface_pytorch] TypeError: 'float' object cannot be interpreted as an integer (#13)


Maybe you can change your python version to 2.7 .

―

**Comment by LingJiangXie** [comment]
哈哈 这个不是我写的…不过恭喜你 起码你跑出结果啦 我刚接触这个方向 可以多交流 我还在上学 现在在西交读研 公式方面我懂的不太多 但是可以问的人很多 可以加个微信吗
[Image]

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
