### ISSUE TITLE
Myphi is not monotonically decreasing ?

### ISSUE THREAD

**Issue by ywu36** [clcarwin/sphereface_pytorch#23]
Dear clcarwin,

According to the original authors of sphereface, the "myphi" need to be a monotonically decreasing function. However, it is not in this implementation.

I'm wondering whether this will affect the final results of verification? And may I know the reason why you simplify the myphi?

Best regards,
Yuhang

**Comment by clcarwin** [comment]
myphi(x) is monotonically decreasing when x>=0.
