### ISSUE TITLE
stuck during training

### ISSUE THREAD

**Issue by fluctlux** [clcarwin/sphereface_pytorch#30]
Thanks for you codes.It really helpful.
I use cleaned CASIA-WebFace, and have 455594 photos.After one epoch train,it stuck at 
04:26:07 Te=0 Loss=8.7917 | AccT=2.0000% (12200/454469) 8.2977 16.70 888

when i use interrupt ,the program stop at  ''
File "train.py", line 142, in <module>
    train(epoch,args)
  File "train.py", line 103, in train
    img,label = ds.get()
  File "/sphereface/dataset.py", line 113, in get
    index,imageshape,labelshape,pathlist = self.result.get()''

By the way,it always remain
 ''raise BadZipFile("Bad magic number for file header")zipfile.BadZipFile: Bad magic number for file header''  and
 ''zipfile.BadZipFile: File name in directory 'CASIA-WebFace/1813440/030.jpg' and header b'CASIA-WebFace/0110168/158.jpg' differ.''
 is there something wrong? How to solve this issue?Thank you.

**Comment by zhao181** [comment]
How did you solve this problem? My training procedure also raise BadZipFile

**Comment by fluctlux** [comment]
My problem solved since I change Python3.5 to Python2.7
